export const Strings = {
  app: {
    name: 'QuoteVault',
    tagline: 'Discover. Collect. Inspire.',
  },
  auth: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome Back',
    getStarted: 'Get Started',
    sendResetLink: 'Send Reset Link',
    resetEmailSent: 'Password reset email sent!',
    name: 'Full Name',
  },
  home: {
    quoteOfTheDay: 'Quote of the Day',
    categories: 'Categories',
    trending: 'Trending',
    forYou: 'For You',
    seeAll: 'See All',
  },
  categories: {
    motivation: 'Motivation',
    love: 'Love',
    success: 'Success',
    wisdom: 'Wisdom',
    humor: 'Humor',
    life: 'Life',
    friendship: 'Friendship',
    happiness: 'Happiness',
  },
  favorites: {
    title: 'Favorites',
    empty: 'No favorites yet',
    emptySubtext: 'Start saving quotes you love!',
  },
  collections: {
    title: 'Collections',
    create: 'Create Collection',
    name: 'Collection Name',
    empty: 'No collections yet',
    emptySubtext: 'Create your first collection!',
    addTo: 'Add to Collection',
    removeFrom: 'Remove from Collection',
  },
  search: {
    placeholder: 'Search quotes or authors...',
    noResults: 'No quotes found',
    tryDifferent: 'Try a different search term',
  },
  profile: {
    title: 'Profile',
    editProfile: 'Edit Profile',
    avatar: 'Avatar',
    displayName: 'Display Name',
    settings: 'Settings',
    about: 'About',
    version: 'Version',
  },
  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    fontSize: 'Font Size',
    notifications: 'Notifications',
    dailyQuote: 'Daily Quote Notification',
    notificationTime: 'Notification Time',
    account: 'Account',
    deleteAccount: 'Delete Account',
  },
  share: {
    title: 'Share Quote',
    asText: 'Share as Text',
    asImage: 'Share as Image',
    saveImage: 'Save Image',
    selectStyle: 'Select Card Style',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'Please check your internet connection.',
    invalidEmail: 'Please enter a valid email address.',
    weakPassword: 'Password must be at least 6 characters.',
    passwordMismatch: 'Passwords do not match.',
    invalidCredentials: 'Invalid email or password.',
    emailInUse: 'This email is already registered.',
  },
  common: {
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    done: 'Done',
    retry: 'Retry',
    pullToRefresh: 'Pull to refresh',
  },
};

